version: "3.3"
services:
  app:
    build: ./src
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    enviroment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbdesafio5
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789